name: If Condition Test
on: push
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:  
      # ${{}}, ""が動作するかの確認(Test1 ~ Test3)
      - name: Test1
        if: ${{ false }}
        run: echo "Test1 Pass"

      - name: Test2
        if: "${{ false }}"
        run: echo "Test2 Pass"

      - name: Test3
        if: false
        run: echo "Test3 Pass"

      # 否定演算子を使う場合は${{}}または""などのエスケープが必要（Test4 ~ Test6）
      - name: Test4
        if: ${{ !true }}
        run: echo "Test4 Pass"

      - name: Test5 
        if: "!true"
        run: echo "Test5 Pass"
        
      # - name: Test6 # 実行できないのでコメントアウト
      #   if: !true
      #   run: echo "Test6 Pass"

      - name: Test7 # 式全体をエスケープ、一部を${{}}でネスト
        if: "${{ false }} == true"
        run: echo "Test7 Pass"

      - name: Test8 # 一部を${{}}でネスト
        if: ${{ false }} == true
        run: echo "Test8 Pass"

      - name: Test9  # 式全体を${{}}でネスト
        if: ${{ false == true }}
        run: echo "Test9 Pass"

      - name: Test10 # 式全体をエスケープ、式の一部を${{}}でネスト、式に否定演算子
        if: "${{ !true }} == true"
        run: echo "Test10 Pass"

      - name: Test11 # 式の一部を${{}}でネスト、式に否定演算子
        if: ${{ !true }} == true
        run: echo "Test11 Pass"

      - name: Test12 # 式全体を${{}}でネスト、式に否定演算子
        if: ${{ !true == true }}
        run: echo "Test12 Pass"
      