name: If Condition Test
on: push
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:  
      # ${{}}, ""が動作するかの確認(Test1 ~ Test3)
      - name: Test1
        if: ${{ false }}
        run: echo "Test1 Pass"
      - name: Test2
        if: "${{ false }}"
        run: echo "Test2 Pass"
      - name: Test3
        if: false
        run: echo "Test3 Pass"
      # NOT（!）の場合は${{}}または""などのエスケープが必要（Test4 ~ Test6）
      - name: Test4
        if: ${{ !true }}
        run: echo "Test4 Pass"
      - name: Test5
        if: "!true"
        run: echo "Test5 Pass"
      # - name: Test6
      #   if: !true
      #   run: echo "Test6 Pass"
      # 式全体をエスケープ、一部を${{}}でネスト
      - name: Test7
        if: "${{ false }} == true"
        run: echo "Test7 Pass"
      # 一部を${{}}でネスト
      - name: Test8
        if: ${{ false }} == true
        run: echo "Test8 Pass"
      # 式全体を${{}}でネスト
      - name: Test9
        if: ${{ false == true }}
        run: echo "Test9 Pass"
      # 式全体をエスケープ、式の一部を${{}}でネスト、式にNOT節
      - name: Test10
        if: "${{ !true }} == true"
        run: echo "Test10 Pass"
      # 式の一部を${{}}でネスト、式にNOT節
      - name: Test11
        if: ${{ !true }} == true
        run: echo "Test11 Pass"
      # 式全体を${{}}でネスト、式にNOT節
      - name: Test12
        if: ${{ !true == true }}
        run: echo "Test12 Pass"
      